// app/head.tsx
export default function Head() {
  return (
    <>
      <title>Jun Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png?v=2" type="image/png" />
    </>
  );
}
